on:
  push:
    tags:
      - "v*"
  
name: Release Stona

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: cedrickring/golang-action@1.6.0
        with: 
          args: make build
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            New Release ( ${{ github.ref }} )
          draft: false
          prerelease: false
      